language: go
go:
- 1.8
before_install:
- sudo add-apt-repository ppa:masterminds/glide -y
- sudo apt-get update -q
- sudo apt-get install glide -y
deploy:
  provider: releases
  api_key:
    secure: UCZA08g3fwXEhGh8T63QMww9e5RwdZ1LAH37qTrx43bqaWpMMUKUYj0kNXhG+Lu/BRjTs5LWVhXNIEc1hr8vXID2jhHnF1NjvK/SuXlxMF+aN8UxDm8DCYnWRXmQNv+lPFZ4LwCsd+UhqrPkYODa30EuQo/sYMwH/NnyRm9JLKXjrLDvHeTfNqZ8lCY7bzb7dfDT6Amd3+pN39b+qCKmzWe7L65i1FUs7HzgT5tXwyIco7KKbzl1nwBENRSrKQlP2jnKcaOohlObL4vkYgDEhyf+JTh6OJERApRbhMOZ+eZFQKiwb6AzjAifyVc4imD/RPCJAsiXMvJmQ+b5MgBwhR5X8GGm978qzvHB2KhHRoRHeyMeqJKx48ya/1hRb364b6VUNVx4gn4EBysTunJbMvnWqdOctRBsdsnRXD5dRBSni0pD6KEh8sIVnmj145TrTU3Tla0wrE/MCtRCUWu/XyY1K35v9CI/l/fOJ7xxhxLeeBAOFkuHbl1ZglPkJXNOavJnSsLgnjYO4kNH4Ge7yEcrDMfOg04qTQE4JoqF+1qAJmvv5aronEVpNAXB657YQjKHMHtBlY8XLEl2g8stAEItoIjIYD+yFSWW9+V4HCgu7Jv9nkzjQC9y4kDIqEpsSKltRfHkylJeM1+jK+R9kd3PYI1IeFq8/k6fgy90kZY=
  file: 
   - build/dist/ferrariworker.linux-amd64.tar.gz
   - build/dist/ferrariworker.darwin-amd64.tar.gz
  on:
    go: 1.8
    tags: true
